### ISSUE TITLE
I2C using pdma and scatter_gather table doesn't send STOP signal at the end of transmission.

### ISSUE THREAD

**Issue by gavinfree** [OpenNuvoton/NUC121_125BSP#4]
I am using NUC121LC2AE, i2c itself works just fine. i2c with pdma in basic mode works just fine.
But i2c with pdma in scatter_gather mode doesn't send STOP signal and the bus isn't free. The SCL
still give out clock signal.

**Comment by egbert-h** [comment]
HI,

It seems that something pull the SDA to LOW so that the I2C Master cannot send STOP signal.

Could you detail more in transferring?

These scatter gather tables of PDMA contain different direction in transfer? 

Is the transferring is Master Write or Master read slave?

notice:
1. The field, OPMODE, in last scatter-gather table should be set to PDMA_OP_BASIC.
2. While doing Master Read transfer, PDMA does not support address stage after START signal.
  PDMA only supports the transfer in data stage after address stage.  
3. Setting for PDMA with I2C in example, I2C_PDMA_TRX, also can be a reference.

**Comment by gavinfree** [comment]
HI,
 Thanks for reply. I changed the last mode to basic and everything goes on well. Thanks for your advice.


And yet there is another problem.
![bug](https://user-images.githubusercontent.com/21150848/88409903-2f7cf500-ce08-11ea-8c19-92b70ca215cf.jpg)
During my last usb asyn audio test. I used EP2 as feedback iso in and EP3 as iso out .But the buff setting for EP3 seems
uncorrect and EP2 was covered by wrong data. During  my single step debug, the buff address changed immediately 
after setting so I got no idea. Hoping ur reply. Thanks a lot !

**Comment by egbert-h** [comment]
HI, 
The address must be **8's multiple**.
![image](https://user-images.githubusercontent.com/39821023/88522016-5f0a4800-d028-11ea-88d8-5719824adaa5.png)

You can refer to the setting in the example, USBD_Audio_NAU8822, in BSP.

Hope it helpful.
